{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failure"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/PexipInfinityClient\/documentation\/PexipInfinityClient\/FailureEvent","preciseIdentifier":"s:19PexipInfinityClient12FailureEventV","text":"FailureEvent"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/pexipinfinityclient\/conferenceclientevent\/failure(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/PexipInfinityClient\/documentation\/PexipInfinityClient\/ConferenceClientEvent\/failure(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Unhandled error occured during the conference call."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failure"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"FailureEvent","preciseIdentifier":"s:19PexipInfinityClient12FailureEventV"},{"kind":"text","text":")"}],"title":"ConferenceClientEvent.failure(_:)","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"s:19PexipInfinityClient010ConferenceC5EventO7failureyAcA07FailureE0VcACmF","modules":[{"name":"PexipInfinityClient (macOS)"}]},"hierarchy":{"paths":[["doc:\/\/PexipInfinityClient\/documentation\/PexipInfinityClient","doc:\/\/PexipInfinityClient\/documentation\/PexipInfinityClient\/ConferenceClientEvent"]]},"references":{"doc://PexipInfinityClient/documentation/PexipInfinityClient/ConferenceClientEvent/failure(_:)":{"role":"symbol","title":"ConferenceClientEvent.failure(_:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failure"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"FailureEvent","preciseIdentifier":"s:19PexipInfinityClient12FailureEventV"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Unhandled error occured during the conference call."}],"identifier":"doc:\/\/PexipInfinityClient\/documentation\/PexipInfinityClient\/ConferenceClientEvent\/failure(_:)","kind":"symbol","type":"topic","url":"\/documentation\/pexipinfinityclient\/conferenceclientevent\/failure(_:)"},"doc://PexipInfinityClient/documentation/PexipInfinityClient/FailureEvent":{"role":"symbol","title":"FailureEvent","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FailureEvent"}],"abstract":[],"identifier":"doc:\/\/PexipInfinityClient\/documentation\/PexipInfinityClient\/FailureEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FailureEvent"}],"url":"\/documentation\/pexipinfinityclient\/failureevent"},"doc://PexipInfinityClient/documentation/PexipInfinityClient":{"role":"collection","title":"PexipInfinityClient (macOS)","abstract":[{"type":"text","text":"Initiate or connect to conferences hosted on the Pexip Infinity platform using REST API."}],"identifier":"doc:\/\/PexipInfinityClient\/documentation\/PexipInfinityClient","kind":"symbol","type":"topic","url":"\/documentation\/pexipinfinityclient"},"doc://PexipInfinityClient/documentation/PexipInfinityClient/ConferenceClientEvent":{"role":"symbol","title":"ConferenceClientEvent","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConferenceClientEvent"}],"abstract":[{"type":"text","text":"Conference-related events important for the consumer of the SDK."}],"identifier":"doc:\/\/PexipInfinityClient\/documentation\/PexipInfinityClient\/ConferenceClientEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConferenceClientEvent"}],"url":"\/documentation\/pexipinfinityclient\/conferenceclientevent"}}}