{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failure"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/PexipInfinityClient\/documentation\/PexipInfinityClient\/FailureEvent","preciseIdentifier":"s:19PexipInfinityClient12FailureEventV","text":"FailureEvent"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/pexipinfinityclient\/conferenceevent\/failure(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/PexipInfinityClient\/documentation\/PexipInfinityClient\/ConferenceEvent\/failure(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Unhandled error occured during the conference call."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failure"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"FailureEvent","preciseIdentifier":"s:19PexipInfinityClient12FailureEventV"},{"kind":"text","text":")"}],"title":"ConferenceEvent.failure(_:)","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"s:19PexipInfinityClient15ConferenceEventO7failureyAcA07FailureE0VcACmF","modules":[{"name":"PexipInfinityClient (iOS)"}]},"hierarchy":{"paths":[["doc:\/\/PexipInfinityClient\/documentation\/PexipInfinityClient","doc:\/\/PexipInfinityClient\/documentation\/PexipInfinityClient\/ConferenceEvent"]]},"references":{"doc://PexipInfinityClient/documentation/PexipInfinityClient/FailureEvent":{"role":"symbol","title":"FailureEvent","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FailureEvent"}],"abstract":[],"identifier":"doc:\/\/PexipInfinityClient\/documentation\/PexipInfinityClient\/FailureEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FailureEvent"}],"url":"\/documentation\/pexipinfinityclient\/failureevent"},"doc://PexipInfinityClient/documentation/PexipInfinityClient":{"role":"collection","title":"PexipInfinityClient (iOS)","abstract":[{"type":"text","text":"Initiate or connect to conferences hosted on the Pexip Infinity platform using REST API."}],"identifier":"doc:\/\/PexipInfinityClient\/documentation\/PexipInfinityClient","kind":"symbol","type":"topic","url":"\/documentation\/pexipinfinityclient"},"doc://PexipInfinityClient/documentation/PexipInfinityClient/ConferenceEvent/failure(_:)":{"role":"symbol","title":"ConferenceEvent.failure(_:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failure"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"FailureEvent","preciseIdentifier":"s:19PexipInfinityClient12FailureEventV"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Unhandled error occured during the conference call."}],"identifier":"doc:\/\/PexipInfinityClient\/documentation\/PexipInfinityClient\/ConferenceEvent\/failure(_:)","kind":"symbol","type":"topic","url":"\/documentation\/pexipinfinityclient\/conferenceevent\/failure(_:)"},"doc://PexipInfinityClient/documentation/PexipInfinityClient/ConferenceEvent":{"role":"symbol","title":"ConferenceEvent","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConferenceEvent"}],"abstract":[{"type":"text","text":"Conference-related events."}],"identifier":"doc:\/\/PexipInfinityClient\/documentation\/PexipInfinityClient\/ConferenceEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConferenceEvent"}],"url":"\/documentation\/pexipinfinityclient\/conferenceevent"}}}